const CONFIG = {
    titleWeb: "Gửi đến chị người yêu hung dữ của tuôi",
    introTitle: 'TRần Thị Kim Ngân',
    introDesc: `Chị có bt không? Bây h trong tim của em chĩ có mình chị❤❤❤`,
    btnIntro: '^^Chị bấm vào đây nè^^',
    title: 'Có nhửng lúc bé làm cho chị cọc😭😭😭😭BÉ BIẾT LỖI ÒI 😚😚😚',
    desc: 'CHỊ CỌC ĐỪNG QUÁT BÉ NHAAA. THA LỖI CHO BÉ NHA',
    btnYes: 'Thích lắm <33',
    btnNo1: 'Dỗi 20%',
    btnNo2: 'Dỗi 40%',
    btnNo3: 'Dỗi 500%',
    btnNo4: 'Dỗi 60%',
    btnNo5: 'Dỗi 70%',
    btnNo6: 'Chị dỗi nx bé quánh chị á ',
    question: 'Trên thế giới hơn 7 tỉ người mà sao bạn lại yêu mình <3',
    btnReply: 'Gửi cho bạn <3',
    reply: 'Yêu thì yêu mà không yêu thì yêu <33333333',
    mess: 'Mình biết mà 🥰. Yêu bạn nhiều nhiều 😘😘',
    messDesc: 'Tối nay, mình qua đón đi chơi nha.',
    btnAccept: 'Okiiiii lun <3',
    messLink: 'https://m.me' //link mess của các bạn. VD: /dinhkaito
}
